version: '3.2'

services:
  app:
    build:
      dockerfile: docker/php-fpm/Dockerfile
      context: .
    restart: always
    volumes:
      - ./:/app
    environment:
      XDEBUG_CONFIG: "remote_host=192.168.122.1 remote_enable=1"
      PHP_IDE_CONFIG: "serverName=Docker"
    depends_on:
      - mysql
    networks:
      - internal

  nginx:
    image: nginx:alpine
    ports:
      - '4099:80'
    volumes:
      - ./:/app
      - ./docker/nginx/nginx.conf:/etc/nginx/nginx.conf
    depends_on:
      - app
    networks:
      - internal

  mysql:
    image: mysql:5.7.25
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    ports:
      - '3366:3306'
    environment:
      MYSQL_ROOT_PASSWORD: secret
      MYSQL_DATABASE: cto
    volumes:
      - ./.data/mysql/:/var/lib/mysql
    networks:
      - internal

  node:
    image: node:12.16.1
    working_dir: /app
    volumes:
      - ./:/app

networks:
  internal:
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: 192.168.122.0/28